# Generated by Django 4.2.11 on 2025-05-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteurs',
            fields=[
                ('id_acheteur', models.IntegerField(primary_key=True, serialize=False)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nbr_chambre', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('ville', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Agent_immo',
            fields=[
                ('id_agent', models.IntegerField(primary_key=True, serialize=False)),
                ('id_bien', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bien_Immobiliers',
            fields=[
                ('id_bien', models.IntegerField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=30)),
                ('code_postal', models.IntegerField()),
                ('surface', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nb_chambres', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('etat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeurs',
            fields=[
                ('id_vendeur', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien_achete', models.BooleanField()),
                ('bien_visite', models.BooleanField()),
                ('rdv', models.DateField()),
                ('id_acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.acheteurs')),
                ('id_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.agent_immo')),
                ('id_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.bien_immobiliers')),
                ('id_vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.vendeurs')),
            ],
        ),
    ]
