# Generated by Django 4.2.11 on 2025-05-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien_immobiliers',
            name='code_postal',
        ),
    ]
