# Generated by Django 4.2.11 on 2025-05-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0002_remove_bien_immobiliers_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien_immobiliers',
            name='estimation',
            field=models.IntegerField(default=0),
        ),
    ]
