# Generated by Django 4.2.11 on 2025-05-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0003_bien_immobiliers_estimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='rdv',
        ),
        migrations.CreateModel(
            name='Rendez_Vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('id_acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.acheteurs')),
                ('id_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.agent_immo')),
                ('id_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.bien_immobiliers')),
                ('id_vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.vendeurs')),
            ],
        ),
    ]
