# Generated by Django 4.2.11 on 2025-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0004_remove_achat_rdv_rendez_vous'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheteurs',
            name='nom',
            field=models.CharField(default='Manon', max_length=30),
        ),
    ]
