# Generated by Django 4.2.11 on 2025-05-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0005_acheteurs_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='id',
        ),
        migrations.AlterField(
            model_name='achat',
            name='id_bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appli_agence_immo.bien_immobiliers'),
        ),
        migrations.AlterField(
            model_name='acheteurs',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
