# Generated by Django 4.2.11 on 2025-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0006_remove_achat_id_alter_achat_id_bien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheteurs',
            name='id_acheteur',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='acheteurs',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
