# Generated by Django 4.2.11 on 2025-05-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0007_alter_acheteurs_id_acheteur_alter_acheteurs_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achat',
            name='id_bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_agence_immo.bien_immobiliers'),
        ),
    ]
