# Generated by Django 4.2.11 on 2025-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_agence_immo', '0008_achat_id_alter_achat_id_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_immo',
            name='id_bien',
        ),
        migrations.AddField(
            model_name='agent_immo',
            name='nom',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
